name: build lolin
on:
  push:
    # tags:
    #   - 'v*'
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

jobs:

  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # - name: Install packages
    #   run: source tools/ci.sh && ci_esp32_idf44_setup
    # - name: Build LOLIN Boards
    #   run: source tools/ci_lolin.sh && ci_lolin_build
    - name: Change firmware name
      run: python ./tools/lolin_tool.py
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        # tag_name: ${{ github.ref }}
        # name: Release ${{ github.ref }}
        # body: TODO New Release.
        # draft: false
        # prerelease: false
        files: |
          ./ports/esp32/build-*/firmware*.bin


