name: build lolin

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

jobs:

  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf44_setup
    - name: Build LOLIN C3 MINI
      run: source esp-idf/export.sh
          make ${MAKEOPTS} -C mpy-cross
          make ${MAKEOPTS} -C ports/esp32 submodules
          make ${MAKEOPTS} -C ports/esp32 BOARD=LOLIN_C3_MINI

